In [ ]:
# !pip install numpy # Install NumPy if it isn't already

In [1]:
# import numpy
import numpy as np

In [2]:
# What will the shapes be?
a = np.array([1,2,3])
b = np.array([[1,2,3]])
c = np.zeros([3, 1])
d = np.array([[1,2],[3]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """


In [3]:
a.shape

(3,)

In [4]:
a.dtype

dtype('int64')

In [5]:
b.shape

(1, 3)

In [6]:
c.shape

(3, 1)

In [7]:
d.shape

(2,)

In [8]:
d

array([list([1, 2]), list([3])], dtype=object)

In [9]:
e = np.array([4,5,6])
print(a, e)
print(a + e)

[1 2 3] [4 5 6]
[5 7 9]


In [10]:
print(a, 3)
a * 3

[1 2 3] 3


array([3, 6, 9])

In [11]:
broad = np.array([2])
print(a*broad)

[2 4 6]


In [12]:
f = np.stack([a, e], axis=0)
print(f.shape)
f

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
print(f[0])
f[:, 0]

array([1, 4])

In [14]:
print(f.shape, b.shape)
g = np.concatenate([f, b], axis=0)
print(g.shape)
print(g)

(2, 3) (1, 3)
(3, 3)
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [15]:
g[:2, :2]

array([[1, 2],
       [4, 5]])

In [16]:
print(g[:, :, np.newaxis].shape)
print(g[:, np.newaxis, :].shape)

(3, 3, 1)
(3, 1, 3)


In [17]:
print(g)
print(g > 4)
print(g[g > 4])

[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[False False False]
 [False  True  True]
 [False False False]]
[5 6]
